# CI/CD Workflow for ReVerse Application
#
# Required GitHub Secrets:
# - PASSKEY_RP_ID: Domain for WebAuthn/Passkey authentication (e.g., "localhost" for testing)
#
# To add secrets:
# 1. Go to Repository Settings → Secrets and variables → Actions
# 2. Click "New repository secret"
# 3. Add PASSKEY_RP_ID with value "localhost"
#
# See .github/SECRETS.md for detailed instructions

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: appdb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appdb_test
          BETTER_AUTH_SECRET: test-secret-key-min-32-chars-long-for-ci
          BETTER_AUTH_URL: http://localhost:3000
          NODE_ENV: test

      - name: Build application
        run: npm run build
        env:
          PASSKEY_RP_ID: ${{ secrets.PASSKEY_RP_ID }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appdb_test
          BETTER_AUTH_SECRET: test-secret-key-min-32-chars-long-for-ci
          BETTER_AUTH_URL: http://localhost:3000

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: app-template:latest
          build-args: |
            PASSKEY_RP_ID=${{ secrets.PASSKEY_RP_ID }}
            BETTER_AUTH_SECRET=testcisupersecretvalue32charsorlonger
            BETTER_AUTH_URL=http://localhost:3000
            DATABASE_URL=postgresql://postgres:postgres@localhost:5432/appdb_test
          cache-from: type=gha
          cache-to: type=gha,mode=max
